# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=workdog
mod_name=Working Dogs
mod_license=All Rights Reserved
mod_version=0.2.0-lite
mod_group_id=com.github.kmfisk.workdog
mod_authors=fisk, Mnesikos
mod_description=Dogs that do work.

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.2
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1